/* ============================================================
   NEXT BEST AUDIO BOOK — books.js

   ★ AFFILIATE TAG  → update AFFILIATE_TAG below
   ★ OFFER COPY     → update AUDIBLE_OFFER below
   ★ DEFAULT BOOK   → update DEFAULT_INDEX (0 = first in array)
   ★ ADD A BOOK     → add object to the books array
   ★ REMOVE A BOOK  → delete the object
   ★ COVER IMAGES   → visit the Audible page, right-click cover → Copy Image Address
   ============================================================ */

const AFFILIATE_TAG  = 'nextbestaudio-21';           // ← your Amazon Associates tag
const GENIUS_LINK    = 'https://geni.us/nbab-audible'; // ← free trial geo-routed link
const AUDIBLE_OFFER  = 'Start your free 30-day Audible trial'; // ← update with current offer
const DEFAULT_INDEX  = 0;                            // ← which book shows first

const books = [
  {
    id: 1,
    title: 'Fourth Wing',
    subtitle: 'Empyrean, Book 1',
    author: 'Rebecca Yarros',
    narrator: 'Rebecca Soler & Teddy Hamilton',
    coverImage: 'https://m.media-amazon.com/images/I/A1KEOf-coBL._SL500_.jpg',
    duration: '22 hrs 2 mins',
    rating: 4.8,
    reviewCount: '504,987',
    review: 'A breakout fantasy epic that took social media by storm — dragon riders, forbidden romance, and brutal military academia collide in one genuinely thrilling package. Rebecca Soler\'s narration is exceptional, and the pacing keeps you hooked through every twist.',
    badges: ['Trending', 'Bestseller', 'Fan Favourite'],
    audibleUrl: 'https://www.audible.co.uk/pd/Fourth-Wing-Audiobook/B0BXM2FJVD',
    amazonUrl:  'https://www.amazon.com/Fourth-Wing-Empyrean-Book-1/dp/B0BVDJ293G'
  },
  {
    id: 2,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    narrator: 'Ray Porter',
    coverImage: 'https://m.media-amazon.com/images/I/81Nzlrfud+L._SL500_.jpg',
    duration: '16 hrs 10 mins',
    rating: 4.7,
    reviewCount: '241,734',
    review: 'Now a major motion picture starring Ryan Gosling. A lone astronaut wakes with no memory on a mission to save Earth — what unfolds is funny, heartbreaking, and scientifically dazzling. Ray Porter\'s narration is some of the finest you\'ll find anywhere.',
    badges: ['Bestseller', 'Critic\'s Pick', 'Film Adaptation'],
    audibleUrl: 'https://www.audible.co.uk/pd/Project-Hail-Mary-Audiobook/B08G9PRS1K',
    amazonUrl:  'https://www.amazon.com/Project-Hail-Mary/dp/B08GB58KD5'
  },
  {
    id: 3,
    title: 'Atomic Habits',
    subtitle: 'The life-changing million-copy #1 bestseller',
    author: 'James Clear',
    narrator: 'James Clear',
    coverImage: 'https://m.media-amazon.com/images/I/81iss3ldpLL._SL500_.jpg',
    duration: '5 hrs 35 mins',
    rating: 4.8,
    reviewCount: '148,111',
    review: 'The most practical book on behaviour change ever written. Clear\'s systems-over-goals framework is genuinely useful, and hearing it in the author\'s own voice adds real conviction. Short enough to finish on a long walk.',
    badges: ['Bestseller', 'Non-fiction'],
    audibleUrl: 'https://www.audible.co.uk/pd/Atomic-Habits-Audiobook/B01N5ESSKW',
    amazonUrl:  'https://www.amazon.com/Atomic-Habits-James-Clear-audiobook/dp/B07J1PMF1H'
  },
  {
    id: 4,
    title: 'Harry Potter & the Philosopher\'s Stone',
    subtitle: 'Full Cast BBC Edition',
    author: 'J.K. Rowling',
    narrator: 'Full Cast',
    coverImage: 'https://m.media-amazon.com/images/I/51YVgooSJuL._SL500_.jpg',
    duration: '8 hrs 41 mins',
    rating: 4.8,
    reviewCount: '156,233',
    review: 'An entirely new production with hundreds of unique voices and Dolby Atmos sound design — Hugh Laurie as Dumbledore, Riz Ahmed as Snape, Matthew Macfadyen as Voldemort, and Cush Jumbo narrating. The immersive audio makes Quidditch and Hogwarts feel genuinely cinematic. Wear headphones.',
    badges: ['Full Cast', 'Classic', 'Fan Favourite'],
    audibleUrl: 'https://www.audible.co.uk/pd/Harry-Potter-and-the-Philosophers-Stone-Audiobook/B017V4IWVG',
    amazonUrl:  'https://www.amazon.com/Harry-Potter-Philosophers-Stone-Full-Cast/dp/B0F14SX2V2'
  },
  {
    id: 5,
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    narrator: 'Full Cast (BBC Radio)',
    coverImage: 'https://placehold.co/300x450/1565C0/ffffff?text=Hitchhiker%27s+Guide',
    duration: '3 hrs 37 mins',
    rating: 4.8,
    reviewCount: '42,110',
    review: 'The original BBC Radio 4 dramatisation remains the definitive version — Adams\' surreal, perfectly-timed comedy sounds best when heard rather than read. The cast, sound design, and sheer absurdity are impeccable.',
    badges: ['Full Cast', 'Classic', 'Comedy'],
    audibleUrl: 'https://www.audible.co.uk/pd/The-Hitchhikers-Guide-to-the-Galaxy-Audiobook/B004EXKW2A',
    amazonUrl:  'https://www.amazon.co.uk/dp/0330508539'
  },
  {
    id: 6,
    title: 'Lessons in Chemistry',
    subtitle: 'The modern classic multi-million-copy bestseller',
    author: 'Bonnie Garmus',
    narrator: 'Miranda Raison',
    coverImage: 'https://m.media-amazon.com/images/I/51-RGNyz08L._SL500_.jpg',
    duration: '11 hrs 56 mins',
    rating: 4.6,
    reviewCount: '313,945',
    review: 'A chemist-turned-TV-cooking-host in 1960s California — funnier, sharper, and more emotionally gutting than the premise suggests. Raison\'s narration gives the protagonist a steely warmth that makes this adaptation distinctly her own.',
    badges: ['Trending', 'TV Adaptation', 'Bestseller'],
    audibleUrl: 'https://www.audible.co.uk/pd/Lessons-in-Chemistry-Audiobook/B09FBCXMVN',
    amazonUrl:  'https://www.amazon.com/Audible-Lessons-in-Chemistry/dp/B09BVX1BT8'
  },
  {
    id: 7,
    title: 'Iron Flame',
    subtitle: 'Empyrean, Book 2',
    author: 'Rebecca Yarros',
    narrator: 'Rebecca Soler & Teddy Hamilton',
    coverImage: 'https://m.media-amazon.com/images/I/A19tBquzlPL._SL500_.jpg',
    duration: '28 hrs 16 mins',
    rating: 4.7,
    reviewCount: '417,844',
    review: 'The follow-up to Fourth Wing is bigger, darker, and longer — in the best possible way. The dual narration has settled into something genuinely special, and the political intrigue adds real texture to the dragon-riding action.',
    badges: ['Trending', 'Series', 'Fantasy'],
    audibleUrl: 'https://www.audible.co.uk/pd/Iron-Flame-Audiobook/B0CJ5D9MDT',
    amazonUrl:  'https://www.amazon.com/Iron-Flame-Empyrean-Book-2/dp/B0C9V75P93'
  },
  {
    id: 8,
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    narrator: 'Jennifer Kim & Julian Cihi',
    coverImage: 'https://m.media-amazon.com/images/I/81wdWQiZG5L._SL500_.jpg',
    duration: '13 hrs 52 mins',
    rating: 4.4,
    reviewCount: '132,448',
    review: 'A novel about friendship, creativity, and video game design that manages to be one of the most emotionally intelligent books in years. Kim\'s narration captures both the intellectual excitement and the quiet grief with remarkable precision.',
    badges: ['Critic\'s Pick', 'Bestseller'],
    audibleUrl: 'https://www.audible.co.uk/pd/Tomorrow-and-Tomorrow-and-Tomorrow-Audiobook/B09Z6KPHRJ',
    amazonUrl:  'https://www.amazon.com/Tomorrow-and/dp/B09LHXNDSP'
  },
  {
    id: 9,
    title: 'The Thursday Murder Club',
    subtitle: 'Book 1 of 5: Thursday Murder Club Mysteries',
    author: 'Richard Osman',
    narrator: 'Lesley Manville & Marian Keyes',
    coverImage: 'https://m.media-amazon.com/images/I/71BSZeMNc-L._SL500_.jpg',
    duration: '12 hrs 25 mins',
    rating: 4.3,
    reviewCount: '181,963',
    review: 'Soon to be a major Netflix film. Four retirement-home residents who solve cold cases together stumble into a very live murder. Warm, funny, and genuinely clever — Lesley Manville\'s narration is pitch-perfect, and there\'s an exclusive conversation with Richard Osman and Marian Keyes at the end.',
    badges: ['Bestseller', 'Film Adaptation', 'Comedy'],
    audibleUrl: 'https://www.audible.co.uk/pd/The-Thursday-Murder-Club-Audiobook/B089FRTJPR',
    amazonUrl:  'https://www.amazon.com/The-Thursday-Murder-Club/dp/B07V5WPCSK'
  },
  {
    id: 10,
    title: 'James',
    subtitle: 'Winner of the 2025 Pulitzer Prize for Fiction',
    author: 'Percival Everett',
    narrator: 'Dominic Hoffman',
    coverImage: 'https://m.media-amazon.com/images/I/81pEI63-5qL._SL500_.jpg',
    duration: '7 hrs 49 mins',
    rating: 4.6,
    reviewCount: '101,659',
    review: 'Winner of the 2025 Pulitzer Prize, the National Book Award, and the British Book Awards Fiction Book of the Year. A retelling of Huckleberry Finn from Jim\'s perspective — devastating, necessary, and ferociously funny. Hoffman\'s narration is The Guardian\'s Audiobook of the Week.',
    badges: ['Award Winner', 'Trending'],
    audibleUrl: 'https://www.audible.co.uk/pd/James-Audiobook/B0CW1D1LBT',
    amazonUrl:  'https://www.amazon.com/Audible-James/dp/B0CFYMW6G8'
  },
  {
    id: 11,
    title: 'Intermezzo',
    author: 'Sally Rooney',
    narrator: 'Paul Nugent & Aoife McMahon',
    coverImage: 'https://placehold.co/300x450/00695C/ffffff?text=Intermezzo',
    duration: '13 hrs 24 mins',
    rating: 4.4,
    reviewCount: '31,204',
    review: 'Rooney\'s most ambitious novel — two brothers grieving their father, both in complicated love affairs. Richer and more structurally inventive than her earlier work, and the dual narration gives each character a properly distinct inner life.',
    badges: ['Trending', 'Bestseller'],
    audibleUrl: 'https://www.audible.co.uk/pd/Intermezzo-Audiobook/B0D6KLXN9T',
    amazonUrl:  'https://www.amazon.co.uk/dp/0571365450'
  },
  {
    id: 12,
    title: 'A Little Life',
    author: 'Hanya Yanagihara',
    narrator: 'David Pittu',
    coverImage: 'https://placehold.co/300x450/263238/ffffff?text=A+Little+Life',
    duration: '32 hrs 47 mins',
    rating: 4.8,
    reviewCount: '54,109',
    review: 'One of the most emotionally affecting novels of the century — four friends in New York, and the long shadow of one man\'s childhood trauma. Pittu\'s narration is extraordinary, holding you through what is genuinely the most demanding listen on this list.',
    badges: ['Critic\'s Pick'],
    audibleUrl: 'https://www.audible.co.uk/pd/A-Little-Life-Audiobook/B012JTQWPC',
    amazonUrl:  'https://www.amazon.co.uk/dp/1447294157'
  },
  {
    id: 13,
    title: 'The Covenant of Water',
    author: 'Abraham Verghese',
    narrator: 'Soneela Nankani',
    coverImage: 'https://placehold.co/300x450/01579B/ffffff?text=Covenant+of+Water',
    duration: '24 hrs 2 mins',
    rating: 4.8,
    reviewCount: '37,829',
    review: 'A multigenerational family saga set in South India across 77 years — vast, humane, and rich with medical and cultural detail. Nankani\'s narration is extraordinary: warm, precisely inflected, and perfectly suited to the novel\'s sweep.',
    badges: ['Bestseller'],
    audibleUrl: 'https://www.audible.co.uk/pd/The-Covenant-of-Water-Audiobook/B0BYWZCT5P',
    amazonUrl:  'https://www.amazon.co.uk/dp/0802161960'
  },
  {
    id: 14,
    title: 'Demon Copperhead',
    author: 'Barbara Kingsolver',
    narrator: 'Charlie Thurston',
    coverImage: 'https://m.media-amazon.com/images/I/91pIsmXSrVL._SL500_.jpg',
    duration: '21 hrs 3 mins',
    rating: 4.6,
    reviewCount: '150,811',
    review: 'A Pulitzer Prize winner that retells David Copperfield in the opioid-ravaged Appalachian Mountains. Thurston\'s narration is one of the best performances in recent memory — raw, funny, and heartbreaking in equal measure.',
    badges: ['Award Winner', 'Critic\'s Pick', 'Bestseller'],
    audibleUrl: 'https://www.amazon.com/Audible-Demon-Copperhead/dp/B0B2X423CV',
    amazonUrl:  'https://www.amazon.com/Audible-Demon-Copperhead/dp/B0B2X423CV'
  },
  {
    id: 15,
    title: 'The Women',
    author: 'Kristin Hannah',
    narrator: 'Julia Whelan',
    coverImage: 'https://m.media-amazon.com/images/I/9178nJYqRbL._SL500_.jpg',
    duration: '14 hrs 55 mins',
    rating: 4.7,
    reviewCount: '332,743',
    review: 'Vietnam War nurses who came home to no welcome, no recognition, no support. Soon to be a major motion picture. Hannah writes with great emotional intelligence, and Whelan — one of the finest audiobook narrators working today — gives this one absolutely everything she has.',
    badges: ['Trending', 'Bestseller', 'Historical Fiction', 'Film Adaptation'],
    audibleUrl: 'https://www.amazon.com/Audible-The-Women/dp/B0C4ZYR3HQ',
    amazonUrl:  'https://www.amazon.com/Audible-The-Women/dp/B0C4ZYR3HQ'
  }
  ,
  {
    id: 31,
    title: 'It Ends with Us',
    subtitle: 'Book 1 of 2',
    author: 'Colleen Hoover',
    narrator: 'Olivia Song',
    coverImage: 'https://m.media-amazon.com/images/I/91w8b7ug0nL._SL500_.jpg',
    duration: '11 hrs 18 mins',
    rating: 4.7,
    reviewCount: '408,501',
    review: 'The book that launched a thousand TikToks — and earned every one of them. A young woman in a new relationship can\'t stop thinking about her first love, and what unfolds is far more honest and painful than the cover suggests. Now a major motion picture starring Blake Lively. Olivia Song\'s narration is tender and precise.',
    badges: ['Trending', 'Bestseller', 'Film Adaptation', 'Romance'],
    audibleUrl: 'https://www.amazon.com/It-Ends-with-Us-Colleen-Hoover-audiobook/dp/B01GGU0XWC',
    amazonUrl:  'https://www.amazon.com/It-Ends-with-Us-Colleen-Hoover-audiobook/dp/B01GGU0XWC'
  },
  {
    id: 35,
    title: 'Spare',
    author: 'Prince Harry',
    narrator: 'Prince Harry, The Duke of Sussex',
    coverImage: 'https://m.media-amazon.com/images/I/81mc6LwjA1L._SL500_.jpg',
    duration: '15 hrs 37 mins',
    rating: 4.5,
    reviewCount: '116,785',
    review: 'Sunday Times Memoir of the Year 2023. Author-narrated — which means you\'re hearing it directly from the person at the centre of one of the most extraordinary family stories of the century. Whatever your prior view, Harry\'s voice gives the grief, the anger, and the confusion a raw credibility no actor could replicate.',
    badges: ['Trending', 'Bestseller', 'Celebrity'],
    audibleUrl: 'https://www.amazon.com/Audible-Spare/dp/B0BKQQ2PQN',
    amazonUrl:  'https://www.amazon.com/Audible-Spare/dp/B0BKQQ2PQN'
  },
  {
    id: 34,
    title: 'Daisy Jones and the Six',
    author: 'Taylor Jenkins Reid',
    narrator: 'Full Cast',
    coverImage: 'https://m.media-amazon.com/images/I/91ehHrj7ItL._SL500_.jpg',
    duration: '9 hrs 3 mins',
    rating: 4.4,
    reviewCount: '97,416',
    review: 'Told entirely in oral history — interviews, arguments, contradictions — about a fictional 1970s rock band at the peak of their fame and the night it all fell apart. The full cast of 16 narrators makes this feel less like a novel and more like a documentary you can\'t stop listening to. Now a hit Amazon Prime TV series.',
    badges: ['Trending', 'Bestseller', 'TV Adaptation', 'Full Cast'],
    audibleUrl: 'https://www.amazon.com/Daisy-Jones-and-Six-audiobook/dp/B07GX1DPFB',
    amazonUrl:  'https://www.amazon.com/Daisy-Jones-and-Six-audiobook/dp/B07GX1DPFB'
  },
  {
    id: 33,
    title: 'The Seven Husbands of Evelyn Hugo',
    subtitle: 'The Sunday Times Bestseller',
    author: 'Taylor Jenkins Reid',
    narrator: 'Alma Cuervo, Julia Whelan, Robin Miles & cast',
    coverImage: 'https://m.media-amazon.com/images/I/51PqpYKCRnL._SL500_.jpg',
    duration: '12 hrs 10 mins',
    rating: 4.6,
    reviewCount: '277,883',
    review: 'A reclusive Hollywood icon finally agrees to tell the truth about her glamorous, scandalous life — seven husbands, ruthless ambition, and a great forbidden love. The full cast narration is perfectly matched to the story\'s scope and theatricality. Soon to be a Netflix film. A TikTok sensation that fully deserved it.',
    badges: ['Trending', 'Bestseller', 'TV Adaptation', 'Romance'],
    audibleUrl: 'https://www.amazon.com/Seven-Husbands-of-Evelyn-Hugo/dp/B09GPV5R42',
    amazonUrl:  'https://www.amazon.com/Seven-Husbands-of-Evelyn-Hugo/dp/B09GPV5R42'
  },
  {
    id: 32,
    title: 'Verity',
    author: 'Colleen Hoover',
    narrator: 'Vanessa Johansson & Amy Landon',
    coverImage: 'https://m.media-amazon.com/images/I/71o-qUYvuOL._SL500_.jpg',
    duration: '8 hrs 10 mins',
    rating: 4.6,
    reviewCount: '468,131',
    review: 'A struggling writer accepts a job from the husband of an injured bestselling author — and finds an unfinished autobiography never meant to be read. Sexy, twisted, and deeply unsettling. The dual narration between Johansson and Landon gives the story exactly the sinister double-vision it needs. Now a major motion picture.',
    badges: ['Trending', 'Thriller', 'Bestseller', 'Film Adaptation'],
    audibleUrl: 'https://www.amazon.com/Verity-Colleen-Hoover-audiobook/dp/B07Q4XWX8C',
    amazonUrl:  'https://www.amazon.com/Verity-Colleen-Hoover-audiobook/dp/B07Q4XWX8C'
  },
  {
    id: 17,
    title: 'Be Useful',
    subtitle: 'Seven Tools for Life',
    author: 'Arnold Schwarzenegger',
    narrator: 'Arnold Schwarzenegger',
    coverImage: 'https://m.media-amazon.com/images/I/81zi2WoM+XL._SL500_.jpg',
    duration: '6 hrs 19 mins',
    rating: 4.7,
    reviewCount: '5,903',
    review: 'Seven rules for a meaningful life, narrated by the man who actually lived them — bodybuilder, movie star, governor. Schwarzenegger\'s voice is exactly what you\'d expect: direct, earnest, and surprisingly moving. No self-pity, no excuses. One of the most motivating listens on this list.',
    badges: ['Non-fiction', 'Celebrity', 'Bestseller'],
    audibleUrl: 'https://www.amazon.com/Be-Useful-Seven-Tools-Life/dp/B0C2HQRSVY',
    amazonUrl:  'https://www.amazon.com/Be-Useful-Seven-Tools-Life/dp/B0C2HQRSVY'
  },
  {
    id: 22,
    title: 'Alchemy',
    subtitle: 'The Surprising Power of Ideas That Don\'t Make Sense',
    author: 'Rory Sutherland',
    narrator: 'Rory Sutherland',
    coverImage: 'https://m.media-amazon.com/images/I/71Dl5RdUuvL._SL500_.jpg',
    duration: '9 hrs 38 mins',
    rating: 4.6,
    reviewCount: '2,207',
    review: 'Ogilvy vice-chairman Rory Sutherland dismantles the myth of rational decision-making with jaw-dropping examples and genuine wit. Why does Red Bull taste terrible and sell billions? Why do countdown boards at train stations reduce frustration without speeding up trains? Sutherland narrates himself, and the effect is electric.',
    badges: ['Non-fiction', 'Critic\'s Pick'],
    audibleUrl: 'https://www.amazon.com/Alchemy-Rory-Sutherland-audiobook/dp/B07KQGCTRW',
    amazonUrl:  'https://www.amazon.com/Alchemy-Rory-Sutherland-audiobook/dp/B07KQGCTRW'
  },
  {
    id: 29,
    title: 'Company of One',
    subtitle: 'Why Staying Small is the Next Big Thing for Business',
    author: 'Paul Jarvis',
    narrator: 'Sam Woolf',
    coverImage: 'https://m.media-amazon.com/images/I/81IhYF4N0IL._SL500_.jpg',
    duration: '8 hrs 17 mins',
    rating: 4.5,
    reviewCount: '1,921',
    review: 'A genuinely counter-cultural business book: what if growth is the wrong goal? Jarvis makes a calm, methodical case for staying deliberately small — more freedom, more profit, fewer meetings. Essential listening for anyone running their own thing or considering it. Sam Woolf\'s narration is clean and unfussy, letting the ideas do the work.',
    badges: ['Non-fiction', 'Business'],
    audibleUrl: 'https://www.amazon.com/Company-of-One-Paul-Jarvis-audiobook/dp/B07LGD1VMJ',
    amazonUrl:  'https://www.amazon.com/Company-of-One-Paul-Jarvis-audiobook/dp/B07LGD1VMJ'
  },
  {
    id: 27,
    title: 'Shoe Dog',
    subtitle: 'A Memoir by the Creator of Nike',
    author: 'Phil Knight',
    narrator: 'Norbert Leo Butz',
    coverImage: 'https://m.media-amazon.com/images/I/81tXVF9zTqL._SL500_.jpg',
    duration: '13 hrs 21 mins',
    rating: 4.7,
    reviewCount: '63,061',
    review: 'One of Bill Gates\' five favourite books ever written, and it\'s easy to see why. Knight traces Nike from a $50 bet to a $30 billion empire with rare honesty — the failures, the near-collapses, the relationships. Norbert Leo Butz brings exactly the right pace and warmth to what is genuinely one of the great business memoirs.',
    badges: ['Non-fiction', 'Bestseller'],
    audibleUrl: 'https://www.amazon.com/Shoe-Dog-Phil-Knight-audiobook/dp/B01CRJA470',
    amazonUrl:  'https://www.amazon.com/Shoe-Dog-Phil-Knight-audiobook/dp/B01CRJA470'
  }
];
